# Generated by Django 4.1.7 on 2023-02-16 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleproduct', '0004_remove_productimage_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vaiants',
        ),
    ]
