# Generated by Django 4.1.7 on 2023-02-16 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleproduct', '0005_remove_product_vaiants'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='saleproduct.product'),
        ),
        migrations.AddField(
            model_name='productvariants',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='saleproduct.product'),
        ),
    ]
