# Generated by Django 4.1.7 on 2023-02-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleproduct', '0009_product_main_image_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_icon',
            field=models.TextField(blank=True, help_text='Category Icon (Font Awesome) - Example: fa fa-home find more at https://fontawesome.com/icons/', verbose_name='Category Icon'),
        ),
    ]
