# Generated by Django 4.1.7 on 2023-02-17 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleproduct', '0014_remove_subcategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SubCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='saleproduct.subcategory'),
        ),
    ]
