# Generated by Django 4.1.7 on 2023-02-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleproduct', '0016_alter_product_subcategory_alter_product_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='SubCategory',
        ),
        migrations.AddField(
            model_name='productvariants',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
