# Generated by Django 4.1.7 on 2023-02-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleproduct', '0017_remove_product_subcategory_productvariants_is_main_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariants',
            name='sku',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
