# Generated by Django 4.1.7 on 2023-02-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleproduct', '0018_alter_productvariants_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_icon',
            field=models.CharField(blank=True, help_text='Category Icon (Font Awesome) - Example: fa fa-home find more at https://fontawesome.com/icons/', max_length=255, verbose_name='Category Icon'),
        ),
    ]
