# Generated by Django 4.1.7 on 2023-03-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleproduct', '0019_alter_category_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='variation_category',
            field=models.CharField(choices=[('color', 'Color'), ('size', 'Size')], default='color', max_length=50),
        ),
    ]
