# Generated by Django 4.1.7 on 2023-03-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleproduct', '0020_productvariants_variation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='variantImage',
            field=models.ImageField(blank=True, null=True, upload_to='res/image/variants'),
        ),
    ]
