# Generated by Django 4.1.7 on 2023-03-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleproduct', '0021_productvariants_variantimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariants',
            old_name='variantImage',
            new_name='variant_image',
        ),
    ]
