# Generated by Django 4.1.7 on 2023-02-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_useraddressbook_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomation',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
