from django.urls import path
from .views import *

#Urls define
urlpatterns = [
    path('', index, name='index'),
    path('category/<slug:slug>/', category, name='category'),
    path('product/<slug:slug>/', product_detail, name='product_detail'),
    path('brand/<slug:slug>/', brand, name='brand'),
    # path('category/<slug:category_slug>/<slug:brand_slug>/', index, name='product_by_brand'),
    # path('category/<slug:category_slug>/<slug:brand_slug>/<slug:product_slug>/', product_detail, name='product_detail'),
    # path('search/', search, name='search'),
    # path('cart/', cart, name='cart'),
    # path('add-to-cart/', add_to_cart, name='add_to_cart'),
    # path('remove-from-cart/', remove_from_cart, name='remove_from_cart'),
    # path('update-cart/', update_cart, name='update_cart'),
    # path('checkout/', checkout, name='checkout'),
    # path('order-complete/', order_complete, name='order_complete'),
    # path('order-history/', order_history, name='order_history'),
    # path('order-detail/<int:order_id>/', order_detail, name='order_detail'),
    # path('order-cancel/<int:order_id>/', order_cancel, name='order_cancel'),
    # path('order-cancel-confirm/<int:order_id>/', order_cancel_confirm, name='order_cancel_confirm'),
    # path('order-cancel-complete/<int:order_id>/', order_cancel_complete, name='order_cancel_complete'),
    # path('order-return/<int:order_id>/', order_return, name='order_return'),
    # path('order-return-confirm/<int:order_id>/', order_return_confirm, name='order_return_confirm'),
    # path('order-return-complete/<int:order_id>/', order_return_complete, name='order_return_complete'),
    # path('order-replace/<int:order_id>/', order_replace, name='order_replace'),
    # path('order-replace-confirm/<int:order_id>/', order_replace_confirm, name='order_replace_confirm'),
    # path('order-replace-complete/<int:order_id>/', order_replace_complete, name='order_replace_complete'),
    # path('order-return-reason/', order_return_reason, name='order_return_reason'),
    # path('contact/', contact, name='contact'),
    # path('about/', about, name='about'),
    # # path('privacy/', privacy, name='privacy'),
    # # path('terms/', terms, name='terms'),
    # path('faq/', faq, name='faq'),
    # # path('sitemap/', sitemap, name='sitemap'),
    # # path('robots.txt/', robots, name='robots'),
    path('404/', page_not_found, name='page_not_found'),
    path('500/', server_error, name='server_error'),
    path('search/', search, name='search'),
]